### ISSUE TITLE
startpage

### ISSUE THREAD

**Issue by michael-milette** [eberhardt/moodle-block_sitenews#4]
I am confused. Can you tell me which is the page that you consider the "startpage"?

Do you perhaps mean the "Frontpage"? If so, I added it but the theme doesn't support a "Content" content area, only left and right block areas. Is this plugin supposed to be able to add the block to the content areas only if the theme supports a Content block area?

Also, what do you mean by "My Home Page". Do you perhaps mean the Dashboard page?

If you could give me an example of the URL for these pages, I might be able to help you with the English terminology.

**Comment by eberhardt** [comment]
"My Startpage" was a term used by Moodle itself. It means the first page you are shown after login.

**Comment by michael-milette** [comment]
That is configurable in Moodle. It can optionally be the Dashboard or the Front Page.

**Comment by eberhardt** [comment]
News are shown on Frontpage anyway (configurable) there would be no need for such a plugin. Anyway, I have edited and clarified the description in the readme. Moodle used to call it "My Startpage" at the beginning, now it's called Dashboard.

**Comment by michael-milette** [comment]
Hi @eberhardt  

Thank you for the clarification Jan.

Best regards,

Michael
